#Unique name for this workflow
name: Deploy master branch to production org

# Definition when the workflow should run
on:
    push:
      branches: [ master ]
      paths:
        - 'force-app/**'
    workflow_dispatch:
      inputs:
       logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
        - info
        - warning
        - debug
env:
  DEVHUB_SFDX_URL: force://PlatformCLI::5Aep861FpKlGRwv8KA7hsW5oNBYlaw2im9x6Bio0bkfPhWnm77TR92TDMyt1jHykzKz3LLmazSi66lPYwz5AvmK@sgummalla-service-cloud-org.my.salesforce.com
  
# Jobs to be executed
jobs:
  source-deploy:
    runs-on: ubuntu-latest

    steps:
      # Store secret for dev hub
      - name: "print sfdx url"
        run: |
            echo 'Suman'
            echo "$HOME/sfdx/bin" >> $GITHUB_PATH
            echo $DEVHUB_SFDX_URL
            echo $GITHUB_PATH

        
